const LOGIN_USER_API_SAGA = 'LOGIN_USER_API_SAGA';
const ADD_MENBER_WITH_KEYWORD_SAGA = 'ADD_MENBER_WITH_KEYWORD_SAGA';
const GET_USER_BY_PROJECT_ID_API_SAGA = 'GET_USER_BY_PROJECT_ID_API_SAGA';
const REMOVE_USER_FROM_TASK_API_SAGA = 'REMOVE_USER_FROM_TASK_API_SAGA';
const ASSIGN_USER_TASK_API_SAGA = 'ASSIGN_USER_TASK_API_SAGA';

const GET_PROJECT_CATEGORY_API_SAGA = 'GET_PROJECT_CATEGORY_API_SAGA';
const CREATE_PROJECT_API_SAGA = 'CREATE_PROJECT_API_SAGA';
const GET_PROJECT_API_SAGA = 'GET_PROJECT_API_SAGA';
const PUT_PROJECT_API_SAGA = 'PUT_PROJECT_API_SAGA';
const DEL_PROJECT_API_SAGA = 'DEL_PROJECT_API_SAGA';
const ASSIGN_USER_PROJECT = 'ASSIGN_USER_PROJECT';
const REMOVE_USER_FROM_PROJECT = 'REMOVE_USER_FROM_PROJECT';
const GET_PROJECT_DETAIL_API = 'GET_PROJECT_DETAIL_API';

const GET_STATUS_API = 'GET_STATUS_API';
const GET_TASK_TYPE_API = 'GET_TASK_TYPE_API';
const GET_PRIORITY_API = 'GET_PRIORITY_API';
const CREATE_TASK_API = 'CREATE_TASK_API';
const UPDATE_TASK_API = 'UPDATE_TASK_API';
const DELETE_TASK_API = 'DELETE_TASK_API';
const GET_TASK_DETAIL_API = 'GET_TASK_DETAIL_API';


export {
    LOGIN_USER_API_SAGA,
    ADD_MENBER_WITH_KEYWORD_SAGA,
    GET_USER_BY_PROJECT_ID_API_SAGA,
    REMOVE_USER_FROM_TASK_API_SAGA,
    ASSIGN_USER_TASK_API_SAGA,

    GET_PROJECT_CATEGORY_API_SAGA,
    CREATE_PROJECT_API_SAGA,
    GET_PROJECT_API_SAGA,
    PUT_PROJECT_API_SAGA,
    DEL_PROJECT_API_SAGA,
    ASSIGN_USER_PROJECT,
    REMOVE_USER_FROM_PROJECT,
    GET_PROJECT_DETAIL_API,
    GET_TASK_DETAIL_API,

    GET_STATUS_API,
    GET_TASK_TYPE_API,
    GET_PRIORITY_API,
    CREATE_TASK_API,
    UPDATE_TASK_API,
    DELETE_TASK_API,
}