const ADD_LOADING = 'ADD_LOADING';
const REMOVE_LOADING = 'REMOVE_LOADING';

const PUSH_NAVIGATE = 'PUSH_NAVIGATE';

const PUSH_USER = 'PUSH_USER';

const SET_PROJECT_CATEGORY = 'SET_PROJECT_CATEGORY';
const SET_ALL_PROJECT = 'SET_ALL_PROJECT'

export {
    ADD_LOADING,
    REMOVE_LOADING,

    PUSH_NAVIGATE,

    PUSH_USER,

    SET_PROJECT_CATEGORY,
    SET_ALL_PROJECT,
};