const ADD_LOADING = 'ADD_LOADING';
const REMOVE_LOADING = 'REMOVE_LOADING';

const PUSH_NAVIGATE = 'PUSH_NAVIGATE';

const PUSH_USER = 'PUSH_USER';

export {
    ADD_LOADING,
    REMOVE_LOADING,

    PUSH_NAVIGATE,

    PUSH_USER
};