const ADD_LOADING = 'ADD_LOADING';
const REMOVE_LOADING = 'REMOVE_LOADING';

const PUSH_NAVIGATE = 'PUSH_NAVIGATE';

const PUSH_USER = 'PUSH_USER';
const PUSH_MEMBER = 'PUSH_MEMBER';
const PUSH_USER_BY_PROJECTID = 'PUSH_USER_BY_PROJECTID';

const SET_PROJECT_CATEGORY = 'SET_PROJECT_CATEGORY';
const SET_ALL_PROJECTS = 'SET_ALL_PROJECTS';
const SET_PROJECT = 'SET_PROJECT';
const SET_PROJECT_DETAIL = 'SET_PROJECT_DETAIL';

const SET_TASK_TYPE = 'SET_TASK_TYPE';
const SET_STATUS = 'SET_STATUS'
const SET_PRIORITY = 'SET_PRIORITY';
const RESET_TASK_FORM = 'RESET_TASK_FORM';
const SET_TASK_DETAIL = 'SET_TASK_DETAIL';
const UPDATE_TASK_DETAIL = 'UPDATE_TASK_DETAIL';

const OPEN_DRAWER = 'OPEN_DRAWER';
const CLOSE_DRAWER = 'CLOSE_DRAWER';
const SET_HANDLE_SUBMIT = 'SET_HANDLE_SUBMIT'


export {
    ADD_LOADING,
    REMOVE_LOADING,

    PUSH_NAVIGATE,

    PUSH_USER,
    PUSH_MEMBER,
    PUSH_USER_BY_PROJECTID,

    SET_PROJECT_CATEGORY,
    SET_ALL_PROJECTS,
    SET_PROJECT,
    SET_PROJECT_DETAIL,

    SET_TASK_TYPE,
    SET_PRIORITY,
    SET_STATUS,
    RESET_TASK_FORM,
    SET_TASK_DETAIL,
    UPDATE_TASK_DETAIL,

    OPEN_DRAWER,
    CLOSE_DRAWER,
    SET_HANDLE_SUBMIT,
};