const LOGIN_USER_API_SAGA = 'LOGIN_USER_API_SAGA';

const GET_PROJECT_CATEGORY_API_SAGA = 'GET_PROJECT_CATEGORY_API_SAGA';
const CREATE_PROJECT_API_SAGA = 'CREATE_PROJECT_API_SAGA';
const GET_PROJECT_API_DATA = 'GET_PROJECT_API_DATA';

export {
    LOGIN_USER_API_SAGA,

    GET_PROJECT_CATEGORY_API_SAGA,
    CREATE_PROJECT_API_SAGA,
    GET_PROJECT_API_DATA,
}